//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace createClientToSky.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTES_PARA_SKY
    {
        public int ID_CLIENTE { get; set; }
        public string NO_CLIENTE { get; set; }
        public string NO_TARJETA { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDOS { get; set; }
        public string DIRECCION { get; set; }
        public int ID_SECTOR { get; set; }
        public string TELEFONO { get; set; }
        public string CELULAR { get; set; }
        public int ID_GENERO { get; set; }
        public int ID_ESTADO_CIVIL { get; set; }
        public string CORREO_E { get; set; }
        public int ID_TIENDA { get; set; }
        public int ID_OCUPACION { get; set; }
        public int ID_NIVEL_EDUCACION { get; set; }
        public System.DateTime FECHA_NACIMIENTO { get; set; }
        public System.DateTime FECHA_AFILIACION { get; set; }
        public int TOTAL_PTOS_GANADOS { get; set; }
        public int TOTAL_PTOS_REDIMIDOS { get; set; }
        public int TOTAL_PTOS_VENCIDOS { get; set; }
        public decimal TOTAL_COMPRAS { get; set; }
        public int CANTIDAD_VISITAS { get; set; }
        public Nullable<System.DateTime> FECHA_ULT_COMPRA { get; set; }
        public int PTOS_GANADOS { get; set; }
        public int PTOS_REDIMIDOS { get; set; }
        public int PTOS_VENCIDOS { get; set; }
        public int PTOS_DISPONIBLES { get; set; }
        public decimal COMPRAS { get; set; }
        public Nullable<System.DateTime> FECHA_ULT_REDENCION { get; set; }
        public string USUARIO { get; set; }
        public System.DateTime FECHAHORA { get; set; }
        public string INACTIVO { get; set; }
        public string EMPLEADO { get; set; }
        public Nullable<int> PTOS_PROMOCIONES { get; set; }
        public string NUMERO_ASOCIADO { get; set; }
        public string PARTICIPANTE { get; set; }
        public Nullable<bool> USADO { get; set; }
    }
}
